### PR TITLE
Add some tips for Windows virtual machine users

### PR DESCRIPTION
**Pull request by zmrui**
Also in 'Install the s2e-env', two commands are reversed.

### CODE REVIEW

**Comment by lisongxu** [comment]
@JeffShao96 How you think about the changes? Thanks

**Comment by JeffShao96** [comment]
I'll discuss with Mingrui.

Thank you
Jianfei Shao

**Review by lisongxu — APPROVED** [review]
Thanks, Mingrui

**Review by JeffShao96 — APPROVED** [review]
I

**Review by JeffShao96 — APPROVED** [review]

**Pull request merged**
